parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     vidlis
    database_user:     root
    database_password: GyVEQbRgzxx3

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt
    memcache_active: true
    hostMemcache: localhost
    portMemcache: 11211
    youtubeAPIKey: AIzaSyBhuf4T4RqCLlirmGfMNPlwGgq0uzRdH2M
    OAUTH2_CLIENT_ID: 645324087510.apps.googleusercontent.com
    OAUTH2_CLIENT_SECRET: r-fE2OtqjhEmWedynoFRzoaa
    urlNode: 37.59.63.129:8080
    javaBin:                /usr/bin/java

twig:
    globals:
        crawlable: ""
        ua_google_analytics: "UA-45678438-1"
        domain_name: "http://vidlis.fr"
        urlNode:      %urlNode%
